#!/usr/bin/with-contenv bash

for s in /assets/functions/*; do source $s; done
PROCESS_NAME="nedi-monitor"
DAEMON=/data/nedi/moni.pl
DAEMON_ARGS="-D"

check_container_initialized
check_service_initialized init
liftoff

print_info "Starting nedi-monitor (Nedi ${NEDI_VERSION} Community Edition)"
silent exec s6-setuidgid nedi $DAEMON $DAEMON_ARGS
